services:
  app:
    image: boxdice/graphql-demo
    build: .
    container_name: graphql-demo
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - TOKEN_ENDPOINT=${TOKEN_ENDPOINT}
      - AGENCY_NAME=${AGENCY_NAME}
      - DEVELOPER_GRAPHQL_ENDPOINT=${DEVELOPER_GRAPHQL_ENDPOINT}
      - DEBUG=App
      - SCHEMA_URL=${SCHEMA_URL}
      - CONCURRENCY=${CONCURRENCY}
      - PAUSE_BETWEEN_REQUESTS=${PAUSE_BETWEEN_REQUESTS}
      - DATABASE_URL=postgres://docker:docker@localhost:5432/graphql_demo
      - RESET_DATABASE=${RESET_DATABASE}
      - COLLECTION_TYPES=${COLLECTION_TYPES}
    ports:
      - "5432:5432"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: ["./entrypoint.sh"]
