version: '3.8'
services:
  app:
    image: boxdice/graphql-demo
    build: .
    container_name: graphql-demo
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - TOKEN_ENDPOINT=${TOKEN_ENDPOINT}
      - AGENCY_NAME=${AGENCY_NAME}
      - DEVELOPER_GRAPHQL_ENDPOINT=${DEVELOPER_GRAPHQL_ENDPOINT}
      - DEBUG=App
      - SCHEMA_URL=${SCHEMA_URL}
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm run start"
